import { expect, test } from "@playwright/test";
import { authorizationHeaders, createNewLocalTestUser, isRecord, requireEnvironment } from "./test-helpers";

test("recorded spending evidence uses real history and restores investigation context", async ({ page }) => {
  await page.clock.install({ time: requireEnvironment("SPENDEAZY_E2E_TEST_CLOCK") });
  await page.setViewportSize({ width: 390, height: 900 });
  await page.goto("/");
  const token = await createNewLocalTestUser(page);
  await expect(page.getByText(/No Categories need attention yet/)).toBeVisible();
  const headers = authorizationHeaders(token);
  const base = `${requireEnvironment("SPENDEAZY_E2E_API_BASE_URL")}/api/v1/users/me`;
  const response = await page.request.post(`${base}/categories`, { headers, data: { name: "Synthetic pattern" } });
  expect(response.ok()).toBe(true);
  const category: unknown = await response.json();
  if (!isRecord(category) || typeof category.id !== "string") throw new Error("Expected Category ID");
  for (const [purchaseDate, amount] of [["2026-06-10", "1000.00"], ["2026-07-10", "1000.00"], ["2026-08-10", "1000.00"], ["2026-09-10", "1500.00"], ["2026-08-25", "9000.00"]]) {
    expect((await page.request.post(`${base}/transactions`, { headers, data: { categoryId: category.id, purchaseDate, amount, description: `Synthetic pattern ${purchaseDate}` } })).ok()).toBe(true);
  }
  await page.getByRole("navigation", { name: "Mobile navigation" }).getByRole("link", { name: "Insights", exact: true }).click();
  await page.getByLabel("Reporting period", { exact: true }).fill("2026-09");
  await expect(page.getByRole("region", { name: "Potential spending patterns" })).toHaveCount(0);
  await page.getByText("Inspect monthly spending", { exact: true }).click();
  const inspect = page.getByRole("button", { name: "Inspect Sep 2026", exact: true });
  await inspect.click();
  const evidence = page.getByRole("dialog");
  await expect(evidence).toContainText("Total: ₱1,500.00");
  await expect(evidence).toContainText("Synthetic pattern 2026-09-10");
  await evidence.getByRole("button", { name: "View Synthetic pattern month’s Transactions" }).click();
  await expect(page).toHaveURL(new RegExp("categoryId=" + category.id));
  await expect(page.getByRole("region", { name: "Transaction summary" }).getByText("₱1,500.00", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Return to Insights" }).click();
  await expect(inspect).toBeFocused();
  await page.getByLabel("Spending point", { exact: true }).selectOption("2026-06");
  const june = page.getByRole("button", { name: "Inspect Jun 2026", exact: true });
  await june.click();
  await expect(evidence).toContainText("Total: ₱1,000.00");
  await evidence.getByRole("button", { name: "View Synthetic pattern month’s Transactions" }).click();
  await expect(page.getByLabel("Reporting period", { exact: true })).toHaveValue("2026-06");
  await expect(page.getByRole("region", { name: "Transaction summary" }).getByText("₱1,000.00", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Return to Insights" }).click();
  await expect(page.getByLabel("Reporting period", { exact: true })).toHaveValue("2026-09");
  await expect(june).toBeFocused();
  await page.getByLabel("Reporting period", { exact: true }).fill("2026-08");
  await page.getByText("Inspect monthly spending", { exact: true }).click();
  await page.getByRole("button", { name: "Inspect Aug 2026", exact: true }).click();
  await expect(evidence).toContainText("Total: ₱10,000.00");
  await expect(evidence).toContainText("Synthetic pattern 2026-08-25");
  await page.keyboard.press("Escape");
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBeLessThanOrEqual(1);
});
