import { expect, test } from "@playwright/test";
import { fileURLToPath } from "node:url";
import { expectFinancialTokenContrast, expectReadableText } from "./financial-accessibility";
import { changeTheme, expectWorkflowSurvivesThemeChange } from "./theme-helpers";
import { authorizationHeaders, createNewLocalTestUser, isRecord, requireEnvironment } from "./test-helpers";

const fixture = fileURLToPath(new URL("./fixtures/spending-journey-encrypted.pdf", import.meta.url));

for (const width of [320, 390, 1440]) {
  test(`Personal spending journey through encrypted Upload and monthly actions at ${width}px`, async ({ page }, testInfo) => {
    test.setTimeout(120_000);
    await page.clock.install({ time: requireEnvironment("SPENDEAZY_E2E_TEST_CLOCK") });
    await page.setViewportSize({ width, height: 900 });
    await page.emulateMedia({ colorScheme: "light" });
    await page.goto("/");
    const token = await createNewLocalTestUser(page);
    await expect(page.getByRole("heading", { name: "Your spending at a glance" })).toBeVisible();
    await expectFinancialTokenContrast(page);
    await expect(page.getByRole("button", { name: "Active Space: Personal" }).filter({ visible: true })).toBeVisible();
    const headers = authorizationHeaders(token);
    const base = `${requireEnvironment("SPENDEAZY_E2E_API_BASE_URL")}/api/v1/users/me`;
    const spaces: unknown = await (await page.request.get(`${base}/spaces`, { headers })).json();
    if (!Array.isArray(spaces) || !isRecord(spaces[0]) || typeof spaces[0].id !== "string") throw new Error("Expected Personal Space");
    const scoped = `${base}/spaces/${spaces[0].id}`;
    const created = await page.request.post(`${scoped}/categories`, { headers, data: { name: "Journey expenses", color: "teal" } });
    expect(created.ok()).toBe(true);
    const category: unknown = await created.json();
    if (!isRecord(category) || typeof category.id !== "string") throw new Error("Expected Category ID");
    expect((await page.request.put(`${scoped}/categories/${category.id}/budget`, { headers, data: { amount: "1000.00", period: "monthly" } })).ok()).toBe(true);
    expect((await page.request.post(`${scoped}/transactions`, { headers, data: { amount: "99.00", purchaseDate: "2026-08-01", description: "Unrelated same-date expense" } })).ok()).toBe(true);
    const navigation = page.getByRole("navigation", { name: width < 768 ? "Mobile navigation" : "Primary navigation" });
    await page.getByLabel("Reporting period", { exact: true }).fill("2026-06");
    await navigation.getByRole("link", { name: "Imports", exact: true }).click();
    let releaseWorker!: () => void;
    const workerReady = new Promise<void>(resolve => { releaseWorker = resolve; });
    let workerLoads = 0;
    await page.route("**/assets/pdf.worker.mjs", async route => {
      workerLoads += 1;
      await workerReady;
      await route.continue();
    });
    await page.locator('input[type="file"]').setInputFiles(fixture);
    try {
      await expect(page.getByRole("button", { name: "Processing", exact: true })).toBeDisabled();
      await expectWorkflowSurvivesThemeChange(page, "Playful", "Light");
      await expectWorkflowSurvivesThemeChange(page, "Technical", "Dark");
      await expect(page.getByRole("button", { name: "Processing", exact: true })).toBeDisabled();
      expect(workerLoads).toBe(1);
    } finally {
      releaseWorker();
    }
    const unlock = page.getByRole("dialog", { name: "PDF password required" });
    await expect(unlock).toBeVisible();
    await unlock.getByLabel("PDF password", { exact: true }).fill("wrong-fictional-password");
    await unlock.getByRole("button", { name: "Open PDF", exact: true }).click();
    await expect(unlock).toContainText("The password you entered is incorrect");
    await unlock.getByLabel("PDF password", { exact: true }).fill("fictional-journey-only");
    await expectWorkflowSurvivesThemeChange(page, "Playful", "Dark");
    await expect(unlock.getByLabel("PDF password", { exact: true })).toHaveValue("fictional-journey-only");
    await page.screenshot({ path: testInfo.outputPath(`password-${width}.png`), fullPage: true });
    await unlock.getByRole("button", { name: "Open PDF", exact: true }).click();
    const rows = width < 768 ? page.getByRole("list", { name: "Transactions to categorize" }) : page.getByRole("table");
    await rows.getByRole("button", { name: "Edit Fictional Separate", exact: true }).click();
    const editor = width < 768 ? page.getByRole("dialog", { name: "Edit Transaction" }) : rows;
    await editor.getByRole("combobox", { name: "Category for Fictional Separate", exact: true }).click();
    await page.getByRole("option", { name: "Journey expenses", exact: true }).click();
    await editor.getByRole("checkbox", { name: "Remember this category" }).check();
    await editor.getByLabel("Amount for Fictional Separate", { exact: true }).fill("-200.02");
    await expectWorkflowSurvivesThemeChange(page, "Technical", "Light");
    await expectWorkflowSurvivesThemeChange(page, "Playful", "Dark");
    await expect(editor.getByLabel("Amount for Fictional Separate", { exact: true })).toHaveValue("-200.02");
    await expect(editor.getByRole("checkbox", { name: "Remember this category" })).toBeChecked();
    await editor.getByLabel("Amount for Fictional Separate", { exact: true }).fill("-200.01");
    await editor.getByRole("button", { name: "Apply & remember", exact: true }).click();
    await expect(page.getByRole("status").filter({ hasText: "Category Rule saved for future imports" })).toBeVisible();
    const assignRepeats = async () => {
      await rows.getByRole("button", { name: "Categorize repeats of FICTIONAL JOURNEY", exact: true }).click();
      const bulk = page.getByRole("dialog", { name: "Categorize repeated descriptions" });
      await expect(bulk.getByRole("status")).toHaveText("3 of 3 matching rows selected");
      await bulk.getByRole("combobox").click();
      await page.getByRole("option", { name: "Journey expenses", exact: true }).click();
      await expectWorkflowSurvivesThemeChange(page, "Technical", "Light");
      await expectWorkflowSurvivesThemeChange(page, "Playful", "Dark");
      await expect(bulk.getByRole("status")).toHaveText("3 of 3 matching rows selected");
      await expect(bulk.getByRole("combobox")).toContainText("Journey expenses");
      await bulk.getByRole("button", { name: "Apply to 3 expenses" }).click();
    };
    await assignRepeats();
    await rows.getByRole("button", { name: "Exclude Fictional Separate", exact: true }).click();
    await rows.getByRole("button", { name: "Include Fictional Separate", exact: true }).click();
    await page.getByRole("button", { name: "Review 4 Transactions", exact: true }).click();
    await expect(page.getByRole("heading", { name: "Review your imported statement" })).toBeFocused();
    await expect(page.getByRole("combobox")).toHaveCount(0);
    await expect(page.getByRole("checkbox")).toHaveCount(0);
    const total = page.getByLabel("Included expense total", { exact: true });
    await expect(total).toContainText("₱2,000.01");
    for (const theme of ["Technical", "Playful"] as const) {
      for (const appearance of ["Light", "Dark", "System"] as const) {
        await expectWorkflowSurvivesThemeChange(page, theme, appearance);
        await expectFinancialTokenContrast(page);
        await expect(total).toContainText("₱2,000.01");
        const expenseTotal = page.getByRole("complementary", { name: "Review insights" }).getByText("₱2,000.01", { exact: true });
        if (width >= 768) {
          await expectReadableText(expenseTotal);
          await expectReadableText(page.getByRole("complementary", { name: "Review insights" }).getByText("Included, categorized debits", { exact: true }));
        }
      }
    }
    const confirm = page.getByRole("button", { name: "Import 4 Transactions", exact: true });
    await page.screenshot({ path: testInfo.outputPath(`review-${width}.png`), fullPage: true });
    await confirm.scrollIntoViewIfNeeded();
    await expect(confirm).toBeInViewport();
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await confirm.click();
    await expect(page.getByRole("heading", { name: "Statement imported" })).toBeFocused();
    await expect(page.getByRole("status").filter({ hasText: "4 expenses saved" })).toContainText("₱2,000.01");
    await expectWorkflowSurvivesThemeChange(page, "Technical", "Light");
    await page.getByRole("button", { name: "View Transactions", exact: true }).click();
    expect(new URL(page.url()).searchParams.get("spaceId")).toBe(spaces[0].id);
    const statementId = new URL(page.url()).searchParams.get("statementImportId");
    expect(statementId).toBeTruthy();
    await expect(page.getByRole("region", { name: "Statement filter" })).toBeVisible();
    await expect(page.getByRole("region", { name: "Transaction summary" })).toContainText("₱2,000.01");
    await expect(page.getByText(/Recorded expense activity matching this view:/)).toContainText("2026-07-31 – 2026-08-03");
    await expect(page.getByText("Unrelated same-date expense", { exact: true })).toHaveCount(0);
    const importedColor = await page.getByText("Journey expenses", { exact: true }).filter({ visible: true }).first()
      .locator('[aria-hidden="true"]').evaluate((element) => getComputedStyle(element).backgroundColor);
    const transactionRoute = page.url();
    await changeTheme(page, "Playful");
    await expect(page).toHaveURL(transactionRoute);
    await expect(page.getByRole("region", { name: "Statement filter" })).toBeVisible();
    await expect(page.getByRole("region", { name: "Transaction summary" })).toContainText("₱2,000.01");
    await expect(page.getByText("Journey expenses", { exact: true }).filter({ visible: true }).first()
      .locator('[aria-hidden="true"]')).toHaveCSS("background-color", importedColor);
    await page.getByRole("button", { name: "Return to monthly view", exact: true }).click();
    await expect(page.getByLabel("Reporting period", { exact: true })).toHaveValue("2026-06");
    await navigation.getByRole("link", { name: "Insights", exact: true }).click();
    await page.getByLabel("Reporting period", { exact: true }).fill("2026-08");
    const summary = page.getByRole("region", { name: "Selected-month recorded spending" });
    await expect(summary.getByText(/Over Budget · ₱0.01 over/)).toHaveCount(1);
    await page.getByText("Explore the last 12 months +", { exact: true }).click();
    const explorer = page.getByRole("region", { name: "Category explorer" });
    await explorer.getByRole("button", { name: "Review Journey expenses: Over Budget", exact: true }).click();
    const accessibleTable = page.getByRole("table", { name: /Monthly spending values from/ });
    await expect(accessibleTable.getByRole("columnheader", { name: "Reporting Period", exact: true })).toHaveCount(1);
    await expect(accessibleTable.getByRole("row").filter({ hasText: "Jul 2026" })).toContainText("₱1,000.00");
    const swatch = explorer.getByRole("button", { name: "Review Journey expenses: Over Budget", exact: true }).locator('[aria-hidden="true"]');
    const categoryColor = await swatch.evaluate((element) => getComputedStyle(element).backgroundColor);
    expect(categoryColor).toBe(importedColor);
    await page.getByLabel("Reporting period", { exact: true }).fill("2026-07");
    await expect(summary.getByText(/At Budget Limit · ₱0.00 remaining/)).toHaveCount(1);
    await explorer.getByRole("button", { name: "Review Journey expenses: At Budget Limit", exact: true }).click();
    await expect(explorer.getByRole("button", { name: "Review Journey expenses: At Budget Limit", exact: true }).locator('[aria-hidden="true"]')).toHaveCSS("background-color", categoryColor);
    await page.getByLabel("Reporting period", { exact: true }).fill("2026-08");
    await explorer.getByRole("button", { name: "Review Journey expenses: Over Budget", exact: true }).click();
    const view = explorer.getByRole("button", { name: "View Journey expenses Transactions" });
    await view.click();
    await expect(page).toHaveURL(new RegExp(`categoryId=${category.id}`));
    await expect(page.getByRole("region", { name: "Transaction summary" })).toContainText("₱1,000.01");
    await page.getByRole("button", { name: "Return to Insights" }).click();
    await expect(view).toBeFocused();
    await expect(page.getByLabel("Reporting period", { exact: true })).toHaveValue("2026-08");
    const edit = explorer.getByRole("button", { name: "Edit Journey expenses Budget" });
    await edit.click();
    const budget = page.getByRole("dialog", { name: "Edit Journey expenses" });
    await expect(budget).toContainText("Saving a new limit also changes historical comparisons");
    await budget.getByRole("textbox", { name: "Monthly Budget for Journey expenses" }).fill("1250.00");
    await changeTheme(page, "Technical");
    await expect(budget.getByRole("textbox", { name: "Monthly Budget for Journey expenses" })).toHaveValue("1250.00");
    await changeTheme(page, "Playful");
    await expect(budget.getByRole("textbox", { name: "Monthly Budget for Journey expenses" })).toHaveValue("1250.00");
    await budget.getByRole("button", { name: /Save/ }).click();
    await expect(edit).toBeFocused();
    await expect(summary.getByText(/Nearing Budget · ₱249.99 remaining/)).toHaveCount(1);
    await page.getByText("Explore the last 12 months +", { exact: true }).click();
    const point = page.getByRole("group", { name: "Inspect chart points" }).getByRole("button", { name: "Jul 2026", exact: true });
    await point.focus();
    await page.keyboard.press("Enter");
    const details = page.getByRole("dialog");
    await expect(details).toContainText("Total: ₱1,000.00");
    await expect(page.getByLabel("Reporting period", { exact: true })).toHaveValue("2026-08");
    await page.keyboard.press("Escape");
    await expect(point).toBeFocused();
    await page.emulateMedia({ colorScheme: "dark" });
    await expect(page.locator("html")).toHaveAttribute("data-theme", "dark");
    await expectFinancialTokenContrast(page);
    await point.click();
    await expect(details.getByRole("button", { name: "View this month" })).toBeInViewport();
    await page.keyboard.press("Escape");
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    // Re-upload the same encrypted bytes: Rule assignment and exact-file protection
    // both survive navigation and the successful Transaction commit.
    await navigation.getByRole("link", { name: "Imports", exact: true }).click();
    await page.locator('input[type="file"]').setInputFiles(fixture);
    await unlock.getByLabel("PDF password", { exact: true }).fill("fictional-journey-only");
    await unlock.getByRole("button", { name: "Open PDF", exact: true }).click();
    await expect(rows).toContainText("Journey expenses");
    const rememberedRow = rows.getByRole(width < 768 ? "listitem" : "row").filter({ hasText: "Fictional Separate" });
    await expect(rememberedRow).toContainText("Journey expenses");
    await expect(rememberedRow.getByText("Rule", { exact: true })).toBeVisible();
    await assignRepeats();
    await page.getByRole("button", { name: "Review 4 Transactions", exact: true }).click();
    await page.getByRole("button", { name: "Import 4 Transactions", exact: true }).click();
    await expect(page.getByText("Statement already imported", { exact: true }).filter({ visible: true })).toBeVisible();
    await expectWorkflowSurvivesThemeChange(page, "Technical", "Dark");
    await expectWorkflowSurvivesThemeChange(page, "Playful", "Light");
    await expect(page.getByText("Statement already imported", { exact: true }).filter({ visible: true })).toBeVisible();
    await expect(page.getByRole("button", { name: "Import 4 Transactions", exact: true })).toBeDisabled();
    const imports: unknown = await (await page.request.get(`${scoped}/statement-imports`, { headers })).json();
    if (!isRecord(imports) || !Array.isArray(imports.items)) throw new Error("Expected import history");
    expect(imports.items).toHaveLength(1);
    expect(imports.items[0]).toMatchObject({ transactionCount: "4", statementDate: "2026-08-31" });
    const saved: unknown = await (await page.request.get(`${scoped}/transactions?statementImportId=${statementId}`, { headers })).json();
    if (!isRecord(saved) || !Array.isArray(saved.items)) throw new Error("Expected saved statement Transactions");
    expect(saved.totalCount).toBe("4");
    expect(saved.items.map((item: unknown) => {
      if (!isRecord(item)) throw new Error("Expected Transaction");
      expect(item).toMatchObject({ categoryId: category.id, source: "imported" });
      return item.amount;
    }).sort()).toEqual(["1000.00", "200.01", "400.00", "400.00"]);
    const rules: unknown = await (await page.request.get(`${scoped}/category-rules`, { headers })).json();
    if (!isRecord(rules) || !Array.isArray(rules.rules)) throw new Error("Expected saved Category Rules");
    expect(rules.rules).toHaveLength(1);
    expect(rules.rules[0]).toMatchObject({ categoryId: category.id, pattern: expect.stringMatching(/^fictional separate$/iu), matchType: "exact" });
    // The plain fixture takes the same real parsing path with no password dialog.
    await page.getByRole("button", { name: "Back to Categorize", exact: true }).click();
    await navigation.getByRole("link", { name: "Dashboard", exact: true }).click();
    await page.getByRole("dialog", { name: "Leave Statement Import?" }).getByRole("button", { name: "Leave Categorize", exact: true }).click();
    await navigation.getByRole("link", { name: "Imports", exact: true }).click();
    await page.locator('input[type="file"]').setInputFiles(fileURLToPath(new URL("./fixtures/spending-journey.pdf", import.meta.url)));
    await expect(rememberedRow).toContainText("Journey expenses");
    await expect(rememberedRow.getByText("Rule", { exact: true })).toBeVisible();
    await expect(unlock).toHaveCount(0);
  });
}
