export const POSTGRES_UNIQUE_VIOLATION = '23505';
export const POSTGRES_FOREIGN_KEY_VIOLATION = '23503';
export const POSTGRES_NOT_NULL_VIOLATION = '23502';
export const POSTGRES_CHECK_VIOLATION = '23514';
export const POSTGRES_INVALID_TEXT_REPRESENTATION = '22P02';
